[env:uno]
platform = atmelavr
board = uno
framework = arduino
; Definir aquí tu clave y ciudad para OpenWeather. Para evitar incluir la clave
; en el repo, reemplaza estos valores localmente o usa variables de entorno.
build_flags = -DOPENWEATHER_API_KEY=\"TU_API_KEY\" -DOPENWEATHER_CITY=\"Ciudad,PA\"
